// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/data/storage/case_db.go

// Package storage is a generated GoMock package.
package storage

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockINotificationDb is a mock of INotificationDb interface.
type MockINotificationDb struct {
	ctrl     *gomock.Controller
	recorder *MockINotificationDbMockRecorder
}

// MockINotificationDbMockRecorder is the mock recorder for MockINotificationDb.
type MockINotificationDbMockRecorder struct {
	mock *MockINotificationDb
}

// NewMockINotificationDb creates a new mock instance.
func NewMockINotificationDb(ctrl *gomock.Controller) *MockINotificationDb {
	mock := &MockINotificationDb{ctrl: ctrl}
	mock.recorder = &MockINotificationDbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINotificationDb) EXPECT() *MockINotificationDbMockRecorder {
	return m.recorder
}

// DeleteRatings mocks base method.
func (m *MockINotificationDb) DeleteRatings(ch chan *DeleteRatingDbResponse, model *DeleteRatingDbModel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteRatings", ch, model)
}

// DeleteRatings indicates an expected call of DeleteRatings.
func (mr *MockINotificationDbMockRecorder) DeleteRatings(ch, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRatings", reflect.TypeOf((*MockINotificationDb)(nil).DeleteRatings), ch, model)
}

// GetRatings mocks base method.
func (m *MockINotificationDb) GetRatings(ch chan *GetRatingDbResponse, model *GetRatingDbModel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetRatings", ch, model)
}

// GetRatings indicates an expected call of GetRatings.
func (mr *MockINotificationDbMockRecorder) GetRatings(ch, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatings", reflect.TypeOf((*MockINotificationDb)(nil).GetRatings), ch, model)
}

// SetRatings mocks base method.
func (m *MockINotificationDb) SetRatings(ch chan *SetRatingDbResponse, model *SetRatingDbModel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRatings", ch, model)
}

// SetRatings indicates an expected call of SetRatings.
func (mr *MockINotificationDbMockRecorder) SetRatings(ch, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRatings", reflect.TypeOf((*MockINotificationDb)(nil).SetRatings), ch, model)
}
