version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: armut-rating-api
    build:
      context: .
      dockerfile: Dockerfile
    image: armut-rating-api
    depends_on:
      - db
    ports:
      - '8000:8000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_CONNECTION_STRING: "postgres://postgres:postgres@db/postgres?sslmode=disable"
    links:
      - db
    volumes:
      - './:/internal'
volumes:
  db:
    driver: local
