// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/data/storage/case_db.go

// Package storage is a generated GoMock package.
package storage

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRatingDb is a mock of IRatingDb interface.
type MockIRatingDb struct {
	ctrl     *gomock.Controller
	recorder *MockIRatingDbMockRecorder
}

// MockIRatingDbMockRecorder is the mock recorder for MockIRatingDb.
type MockIRatingDbMockRecorder struct {
	mock *MockIRatingDb
}

// NewMockIRatingDb creates a new mock instance.
func NewMockIRatingDb(ctrl *gomock.Controller) *MockIRatingDb {
	mock := &MockIRatingDb{ctrl: ctrl}
	mock.recorder = &MockIRatingDbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRatingDb) EXPECT() *MockIRatingDbMockRecorder {
	return m.recorder
}

// GetRatingAverage mocks base method.
func (m *MockIRatingDb) GetRatingAverage(ch chan *GetRatingDbResponse, model *GetRatingDbModel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetRatingAverage", ch, model)
}

// GetRatingAverage indicates an expected call of GetRatingAverage.
func (mr *MockIRatingDbMockRecorder) GetRatingAverage(ch, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRatingAverage", reflect.TypeOf((*MockIRatingDb)(nil).GetRatingAverage), ch, model)
}

// SetRatings mocks base method.
func (m *MockIRatingDb) SetRatings(ch chan *SetRatingDbResponse, model *SetRatingDbModel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRatings", ch, model)
}

// SetRatings indicates an expected call of SetRatings.
func (mr *MockIRatingDbMockRecorder) SetRatings(ch, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRatings", reflect.TypeOf((*MockIRatingDb)(nil).SetRatings), ch, model)
}
